on:
  workflow_call:
    inputs:
      extension:
        type: string
        required: true

jobs:
  apk-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - name: Setup QEMU
#        run: docker run --rm --privileged aptman/qus -s -- -p aarch64
      - name: Build APK
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          file: apkbuild/Dockerfile
          push: false
          load: true
          no-cache: true
          secrets: |
            "APK_PRIVATE_KEY=${{ secrets.APK_PRIVATE_KEY }}"
            "APK_PUBLIC_KEY=${{ secrets.APK_PUBLIC_KEY }}"
          build-args: |
            "APK_SOURCE=php-83/alpine/intl"
      - name: Copy apk from docker image
        run: |        
          CONTAINERID=$(docker run -d "${{ steps.docker_build.outputs.imageid }}" sleep 60)
          docker cp "$CONTAINERID":/packages/ $GITHUB_WORKSPACE
          docker kill "$CONTAINERID"
          ls -al $GITHUB_WORKSPACE/packages
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          tag_name: 'intl-8.3.10'
          make_latest: false
          #body_path: ${{ github.workspace }}-CHANGELOG.txt
          body: "Initial release"
          token: ${{ secrets.DCS_PAT }}
          fail_on_unmatched_files: true
          files: |
            packages/**/php-extensions-intl-8.3.10-r0.apk
      - name: Update APK repo
        run: |
          git checkout gh-pages
          ls -al $GITHUB_WORKSPACE/packages
          docker run --rm -it \
            -v $GITHUB_WORKSPACE/packages/:/packages -w /packages alpine:latest \
            apk index --merge --verbose --update-cache --allow-untrusted --no-interactive -x ./APKINDEX.tar.gz -o ./APKINDEX.tar.gz ./aarch64/*.apk ./x86_64/*.apk \
            && ls -al . \
            && pwd
          ls -al $GITHUB_WORKSPACE/packages/
         
          
          
