on:
  workflow_call:
    inputs:
      extension:
        type: string
        required: true

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension
          path: extension
      - name: Archive extension
        run: |
          mkdir -p assets
          tar -czvf assets/${{ inputs.extension }}-8.3.10-extension-aarch64-alpine.tar.gz extension
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          tag_name: 'intl-8.3.10'
          make_latest: false
          #body_path: ${{ github.workspace }}-CHANGELOG.txt
          body: "Initial release"
          generate_release_notes: true
          token: ${{ secrets.DCS_PAT }}
          fail_on_unmatched_files: true
          files: |
            assets/*.tar.gz

