on:
  workflow_call:
    inputs:
      extension:
        type: string
        required: true

jobs:
  apk-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - name: Setup QEMU
#        run: docker run --rm --privileged aptman/qus -s -- -p aarch64
      - name: Build APK
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          file: apkbuild/Dockerfile
          push: false
          load: true
          no-cache: true
          secrets: |
            "APK_PRIVATE_KEY=${{ secrets.APK_PRIVATE_KEY }}"
            "APK_PUBLIC_KEY=${{ secrets.APK_PUBLIC_KEY }}"
          build-args: |
            "APK_SOURCE=php-83/alpine/intl"
      - name: Copy apk from docker image
        run: |        
          CONTAINERID=$(docker run -d "${{ steps.docker_build.outputs.imageid }}" sleep 60)
          docker cp "$CONTAINERID":/packages/ $GITHUB_WORKSPACE
          docker rm -f "$CONTAINERID"
          ls -al $GITHUB_WORKSPACE/packages
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          tag_name: 'intl-8.3.10'
          make_latest: false
          #body_path: ${{ github.workspace }}-CHANGELOG.txt
          body: "Initial release"
          token: ${{ secrets.DCS_PAT }}
          fail_on_unmatched_files: true
          files: |
            packages/**/php-extensions-intl-8.3.10-r0.apk
      - name: Update APK repo
        run: |
          # Set current directory as a safe directory.
          git config --global --add safe.directory /github/workspace
          ORIGINAL_BRANCH="$(git symbolic-ref --short HEAD)"
          GH_PAGES_BRANCH=gh-pages
          
          # Checkout gh-pages branch
          if ! git fetch -n --no-recurse-submodules --depth=1 origin "$GH_PAGES_BRANCH"; then
            echo "The branch gh-pages doesn't exist."
            exit 1
          fi
          
          git checkout --progress --force -B "$GH_PAGES_BRANCH" refs/remotes/origin/"$GH_PAGES_BRANCH"
          
          # Copy current packages.
          docker run --rm \
            -v "$GITHUB_WORKSPACE/packages:/packages" alpine:latest \
            sh -c "
              apk index --merge --verbose --update-cache --allow-untrusted --no-interactive -x ./APKINDEX.tar.gz -o ./APKINDEX.tar.gz ./aarch64/*.apk ./x86_64/*.apk
              ls -al /packages
            "
          ls -al $GITHUB_WORKSPACE/packages/
          
          git add packages/
          git -c user.name="$GITHUB_ACTOR" -c user.email="$GITHUB_ACTOR@users.noreply.github.com" commit -m "${INPUT_COMMIT_MESSAGE:-Update packages}" && \
            git push origin "$GH_PAGES_BRANCH" || echo Nothing to commit
        
         
          
          
